#!/bin/sh

DIR="$(grep "backupdir=" ~/.compbackup.config | cut -d'=' -f2)"
DATE="$(date +'companion-backup-%Y%m%d.companionconfig')"
config="$(curl http://10.45.0.66:8888/int/full_export)"

test "$config" && echo "$config" > "$DIR/$DATE"
